version: '2.1'

orbs:
  snyk: snyk/snyk@1.4.0
jobs:
  build:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - run: npm ci
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: true
          project: demo-app/circleci-project-setup
          severity-threshold: high
          token-variable: SNYK_TOKEN
workflows: null
